# Generated by Django 2.0 on 2021-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(default=None)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adress_line_1', models.CharField(max_length=100, null=True)),
                ('adress_line_2', models.CharField(max_length=100, null=True)),
                ('poscode', models.CharField(max_length=5, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
