# Generated by Django 2.0 on 2021-04-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210419_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('ic', models.IntegerField(help_text='Format 780506104554.', max_length=13, null=True)),
                ('date_of_birth', models.DateField(default=None)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adress_line_1', models.CharField(max_length=100, null=True)),
                ('adress_line_2', models.CharField(max_length=100, null=True)),
                ('poscode', models.CharField(max_length=5, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.State')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
